const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),cp=require('node:child_process');
const {Countdown,formatTime}=require('../src/timer-core.js');
const {snackState}=require('../src/snack-core.js');
const root=path.resolve(__dirname,'..');
const read=n=>fs.readFileSync(path.join(root,n),'utf8');
test('distribution matches editable sources',()=>cp.execFileSync(process.execPath,['scripts/build.mjs','--check'],{cwd:root}));
test('all JavaScript sources parse',()=>{for(const f of ['timer-core.js','snack-core.js','assets.js','app.js'])new vm.Script(read('src/'+f));});
test('no duplicate HTML ids',()=>{const ids=[...read('index.html').matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);});
test('embedded assets are complete data URLs',()=>{const s={window:{}};vm.runInNewContext(read('src/assets.js'),s,{timeout:2000});const a=s.window.TimerAssets;assert.ok(Object.keys(a).length>=16);for(const [name,url]of Object.entries(a)){const m=/^data:([^;]+);base64,([A-Za-z0-9+/=]+)$/.exec(url);assert.ok(m,name);assert.ok(Buffer.from(m[2],'base64').length>50,name);}assert.equal(a['chew-8.webp'],a['squirrel-ready.webp']);for(const k of ['tidy','meal','bath','out','brush','sleep'])assert.ok(a['next-'+k+'.webp']);});
for(const d of [1000,20000,60000,180000,300000,600000,900000,1200000,1800000,2700000,3600000])test(`exact deadline ${d}`,()=>{let now=1000;const t=new Countdown(()=>now);t.start(d);now+=d-1;assert.equal(t.remaining(),1);assert.equal(t.tick(),false);now++;assert.equal(t.tick(),true);assert.equal(t.tick(),false);});
test('pause freezes remaining time',()=>{let now=1000;const t=new Countdown(()=>now);t.start(20000);now+=4123;t.pause();now+=600000;assert.equal(t.remaining(),15877);t.resume();now+=15877;assert.ok(t.tick());});
test('acknowledgement follows finish',()=>{let now=1;const t=new Countdown(()=>now);t.start(1000);assert.equal(t.acknowledge(),false);now+=1000;t.tick();assert.equal(t.acknowledge(),true);assert.equal(t.status,'acknowledged');});
test('positive fractions do not display zero',()=>assert.equal(formatTime(1),'00:01'));
for(const [ms,phase]of [[0,'reach'],[1999,'reach'],[2000,'chew'],[7999,'chew'],[8000,'settle'],[9999,'settle']])test(`preserved animation phase ${ms}`,()=>assert.equal(snackState(20000,20000-ms).phase,phase));
test('short remainder keeps its deadline',()=>{assert.equal(snackState(11000,100).stepMs,1000);assert.equal(snackState(11000,0).phase,'complete');});
test('long timer uses next tray',()=>assert.equal(snackState(3600000,3000000).pageStart,60));
test('nine visibility choices remain separate from time selection',()=>{const h=read('index.html');assert.equal((h.match(/data-visible-preset="/g)||[]).length,9);assert.ok(h.includes('id="custom-minutes"'));assert.ok(!h.includes('id="current-activity"'));});
test('both direct completion buttons exist',()=>{const h=read('index.html');assert.ok(h.includes('id="finished-restart-button"'));assert.ok(h.includes('id="finished-reset-button"'));});
