const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),cp=require('node:child_process');
const {Countdown,formatTime}=require('../src/timer-core.js');
const {snackState}=require('../src/snack-core.js');
const root=path.resolve(__dirname,'..');
const read=n=>fs.readFileSync(path.join(root,n),'utf8');
test('distribution matches editable sources',()=>cp.execFileSync(process.execPath,['scripts/build.mjs','--check'],{cwd:root}));
test('all JavaScript sources parse',()=>{for(const f of ['timer-core.js','snack-core.js','assets.js','app.js'])new vm.Script(read('src/'+f));});
test('no duplicate HTML ids',()=>{const ids=[...read('index.html').matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);});
test('embedded assets are complete data URLs',()=>{const s={window:{}};vm.runInNewContext(read('src/assets.js'),s,{timeout:2000});const a=s.window.TimerAssets;assert.ok(Object.keys(a).length>=33);for(const [name,url]of Object.entries(a)){const m=/^data:([^;]+);base64,([A-Za-z0-9+/=]+)$/.exec(url);assert.ok(m,name);assert.ok(Buffer.from(m[2],'base64').length>50,name);}assert.equal(a['chew-8.webp'],a['squirrel-ready.webp']);assert.ok(a['apple.svg']);assert.ok(a['elephant-ready.webp']);for(let i=0;i<9;i++){const name='elephant-chew-'+i+'.webp';assert.ok(a[name]);assert.deepEqual(Buffer.from(a[name].slice(a[name].indexOf(',')+1),'base64'),fs.readFileSync(path.join(root,'ato-sukoshi-assets/elephant/upload',name)));}assert.equal(new Set(Array.from({length:9},(_,i)=>a['elephant-chew-'+i+'.webp'])).size,9);for(const k of ['tidy','meal','bath','out','brush','sleep']){assert.ok(a['next-'+k+'.webp']);assert.ok(a['elephant-next-'+k+'.webp']);}});
test('finish scenes switch by character in app source',()=>{const js=read('src/app.js');assert.ok(js.includes('nextScene'));assert.ok(js.includes('elephant-next-'));assert.ok(js.includes('SCENE_ALT[ch.id]'));assert.ok(js.includes('sel=choices()'));assert.ok(js.includes('ch=character()'));assert.ok(js.includes('片付けるぞうさん'));assert.ok(js.includes('片付けるねずみさん'));});
test('character switch lives in sound and display settings',()=>{const h=read('index.html');assert.ok(h.includes('id="extra-settings"'));assert.ok(h.includes('data-character="squirrel"'));assert.ok(h.includes('data-character="elephant"'));assert.ok(h.includes('data-character="mouse"'));assert.ok(h.includes('ねずみさん'));assert.ok(h.indexOf('data-character="elephant"')<h.indexOf('data-character="mouse"'));assert.ok(h.includes('なかまを えらぶ'));assert.ok(!h.match(/data-character=/g)||h.indexOf('extra-settings')<h.indexOf('data-character='));});
test('mouse assets match the upload files',()=>{
  const s={window:{}};
  vm.runInNewContext(read('src/assets.js'),s,{timeout:2000});
  const a=s.window.TimerAssets;
  const upload=path.join(root,'ato-sukoshi-assets/mouse/upload');
  const next=path.join(root,'ato-sukoshi-assets/mouse/next-gen');
  function bytes(name){const url=a[name];assert.ok(url,name);return Buffer.from(url.slice(url.indexOf(',')+1),'base64');}
  assert.deepEqual(bytes('biscuit.svg'),fs.readFileSync(path.join(upload,'biscuit.svg')));
  assert.deepEqual(bytes('mouse-ready.webp'),fs.readFileSync(path.join(upload,'mouse-ready.webp')));
  for(let i=0;i<9;i++){const name='mouse-chew-'+i+'.webp';assert.deepEqual(bytes(name),fs.readFileSync(path.join(upload,name)));}
  assert.equal(new Set(Array.from({length:9},(_,i)=>a['mouse-chew-'+i+'.webp'])).size,9);
  for(const k of ['tidy','meal','bath','out','brush','sleep']){const name='mouse-next-'+k+'.webp';assert.deepEqual(bytes(name),fs.readFileSync(path.join(next,name)));}
});
test('mouse theme is registered beside elephant',()=>{
  const js=read('src/app.js');
  assert.ok(js.includes("id:'mouse'"));
  assert.ok(js.includes("label:'ねずみさん'"));
  assert.ok(js.includes("snack:'ビスケット'"));
  assert.ok(js.includes("snackIcon:'biscuit.svg'"));
  assert.ok(js.includes('mouse-ready.webp'));
  assert.ok(js.includes("chew:i=>'mouse-chew-'+i+'.webp'"));
  assert.ok(js.includes("nextScene:k=>'mouse-next-'+k+'.webp'"));
  assert.ok(js.includes('mouse-next-'));
  for(const alt of ['おもちゃを片付けるねずみさん','ごはんを食べるねずみさん','おふろに入るねずみさん','リュックを背負って出かけるねずみさん','歯みがきするねずみさん','おふとんで眠るねずみさん'])assert.ok(js.includes(alt),alt);
  assert.ok(js.includes('land:[.668,.542]'));
  assert.ok(js.includes('character().land||[.846,.612]'));
});
for(const d of [1000,20000,60000,180000,300000,600000,900000,1200000,1800000,2700000,3600000])test(`exact deadline ${d}`,()=>{let now=1000;const t=new Countdown(()=>now);t.start(d);now+=d-1;assert.equal(t.remaining(),1);assert.equal(t.tick(),false);now++;assert.equal(t.tick(),true);assert.equal(t.tick(),false);});
test('pause freezes remaining time',()=>{let now=1000;const t=new Countdown(()=>now);t.start(20000);now+=4123;t.pause();now+=600000;assert.equal(t.remaining(),15877);t.resume();now+=15877;assert.ok(t.tick());});
test('acknowledgement follows finish',()=>{let now=1;const t=new Countdown(()=>now);t.start(1000);assert.equal(t.acknowledge(),false);now+=1000;t.tick();assert.equal(t.acknowledge(),true);assert.equal(t.status,'acknowledged');});
test('positive fractions do not display zero',()=>assert.equal(formatTime(1),'00:01'));
for(const [ms,phase]of [[0,'reach'],[1999,'reach'],[2000,'chew'],[7999,'chew'],[8000,'settle'],[9999,'settle']])test(`preserved animation phase ${ms}`,()=>assert.equal(snackState(20000,20000-ms).phase,phase));
test('short remainder keeps its deadline',()=>{assert.equal(snackState(11000,100).stepMs,1000);assert.equal(snackState(11000,0).phase,'complete');});
test('long timer uses next tray',()=>assert.equal(snackState(3600000,3000000).pageStart,60));
test('nine visibility choices remain separate from time selection',()=>{const h=read('index.html');assert.equal((h.match(/data-visible-preset="/g)||[]).length,9);assert.ok(h.includes('id="custom-minutes"'));assert.ok(!h.includes('id="current-activity"'));});
test('both direct completion buttons exist',()=>{const h=read('index.html');assert.ok(h.includes('id="finished-restart-button"'));assert.ok(h.includes('id="finished-reset-button"'));});
test('setup hint names the selected next activity',()=>{
  const js=read('src/app.js'),h=read('index.html');
  const next={tidy:'おかたづけ',meal:'ごはん',bath:'おふろ',out:'おでかけ',brush:'はみがき',sleep:'ねんね'};
  const parsed=Object.assign({},vm.runInNewContext('('+js.match(/const NEXT=(\{[^}]+\})/)[1]+')'));
  assert.deepEqual(parsed,next);
  assert.ok(js.includes("$('parent-hint-quote').textContent='「ぜんぶ なくなったら、'+NEXT[sel.next]+'しようね」'"));
  for(const label of Object.values(parsed))assert.ok(('「ぜんぶ なくなったら、'+label+'しようね」').endsWith(label+'しようね」'));
  assert.ok(h.includes('id="parent-hint-quote">「ぜんぶ なくなったら、おかたづけしようね」'));
  assert.equal(h.includes('おしまいね'),false);
  assert.equal(h.includes('広告なし'),false);
  assert.equal(h.includes('親子のための小さな道具'),false);
  assert.equal(h.includes('<footer'),false);
});
test('header pill, how-to link, and hero copy are absent',()=>{
  const h=read('index.html');
  const js=read('src/app.js');
  assert.equal(h.includes('登録しないで'),false);
  assert.equal(h.includes('id="help-button"'),false);
  assert.equal(h.includes('おわりを、いっしょに見つけよう'),false);
  assert.equal(h.includes('id="intro-lead"'),false);
  assert.equal(h.includes('class="intro'),false);
  assert.equal(js.includes('intro-lead'),false);
  assert.equal(js.includes('help-button'),false);
  assert.equal(h.includes('id="help-dialog"'),false);
  assert.equal(h.includes('id="clear-settings"'),false);
  assert.equal(js.includes('help-dialog'),false);
  assert.equal(js.includes('clear-settings'),false);
  assert.equal(js.includes('help-start-text'),false);
  assert.ok(h.includes('id="fullscreen-button"'));
  assert.ok(h.includes('<h1 class="brand-name">あとすこし</h1>'));
  assert.equal((h.match(/<h1\b/g)||[]).length,1);
});
